# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image for tests
        run: docker -t docker-app build ./ --target e2e-test
      
      - name: Install dev dependencies
        run: pip3 install -r requirements-dev.txt
        
      - name: Install app in local environment
        run: pip3 install -e .

      - name: Pull selenium grid
        run: docker pull selenium/standalone-chrome

      - name: Run selenium grid
        run: docker run -d -p 4444:4444 -p 7900:7900 --shm-size="2g" --name selenium-grid selenium/standalone-chrome

      - name: Run container
        run: docker run -d -p 8000:8000 -e PORT=8000 --name my-app docker-app

      - name: export environment variable app ip
        run: export APP_HOST=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' my-app)

      - name: export environment variable app ip
        run: export SELENIUM_GRID_HOST=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' selenium-grid)
        
      - name: Run tests
        run: pytest -k e2e
        env:
          SELENIUM_GRID_PORT: 4444
          APP_PORT: 8000
      
