# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image with test data
        run: docker build -t docker-app ./ --target test-data
      
      - name: Install dev dependencies
        run: pip3 install -r requirements-dev.txt
        
      - name: Install app in local environment
        run: pip3 install -e .

      - name: Pull selenium grid image
        run: docker pull selenium/standalone-chrome

      - name: Run selenium grid container
        run: docker run -d -p 4444:4444 -p 7900:7900 --shm-size="2g" --name selenium-grid selenium/standalone-chrome

      - name: Run application container
        run: docker run -d -p 8000:8000 -e PORT=8000 --name my-app docker-app

      - name: Set up APP_HOST environment variable
        run: export APP_HOST=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' my-app)

      - name: Set up SELENIUM_GRID_HOST environment variable
        run: export SELENIUM_GRID_HOST=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' selenium-grid)
        
      - name: Run e2e tests
        run: pytest -k e2e
        env:
          SELENIUM_GRID_PORT: 4444
          APP_PORT: 8000
  Build-and-push:
    needs: [unit-tests, lint]
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pc_status:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Heroku Docker Container Deploy
      # You may pin to the exact commit or the version.
      # uses: lucassarcanjo/heroku-deploy@1db4c62f6032efe526c12734f18d36669218e5af
      uses: lucassarcanjo/heroku-deploy@2.1.17
      with:
        # Email Linked to your Heroku Account
        email: gv4alex@gmail.com
        # Your Heroku API Key
        api_key: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        # Your Heroku App Name
        app_name:  serene-beyond-15967 
        # Dokerfile path
        dockerfile_path: ./